// <auto-generated />
using System;
using Backend.Database.Auth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324015948_AddedNotificationsAndInvitations")]
    partial class AddedNotificationsAndInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Admin.Entities.PendingJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityDocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdentityReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InstituteCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstituteCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstitutePostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("ProofDocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("IdentityReviewedBy");

                    b.ToTable("PendingJoinRequests");
                });

            modelBuilder.Entity("Backend.Administration.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Seen")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Backend.Administration.Entities.ProfessorInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassPrettyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("IdentityId");

                    b.ToTable("ProfessorInvitations");
                });

            modelBuilder.Entity("Backend.Administration.Entities.UniStaffInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstituteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("InstituteId");

                    b.ToTable("UniStaffInvitations");
                });

            modelBuilder.Entity("Backend.Auth.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PfpUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Backend.Auth.Entities.AuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivateAccountToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivateAccountTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfessorId");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("Backend.Auth.Entities.ClassMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentTerm")
                        .HasColumnType("integer");

                    b.Property<Guid>("InstituteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("LevelOfStudies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxTerms")
                        .HasColumnType("integer");

                    b.Property<int>("MaxYears")
                        .HasColumnType("integer");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("ClassMetadata");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Institute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PfpUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PfpUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("UniClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("UniClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Backend.Auth.Entities.UniClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode")
                        .IsUnique();

                    b.HasIndex("MetadataId", "Number")
                        .IsUnique();

                    b.ToTable("UniClasses");
                });

            modelBuilder.Entity("Backend.Auth.Entities.UniUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InstituteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PfpUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("InstituteId");

                    b.ToTable("UniUsers");
                });

            modelBuilder.Entity("Backend.StudentSpace.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("UniClassId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Backend.Admin.Entities.PendingJoinRequest", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("IdentityReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Identity");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Backend.Administration.Entities.Notification", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithMany("Notifications")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Backend.Administration.Entities.ProfessorInvitation", b =>
                {
                    b.HasOne("Backend.StudentSpace.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithMany("ProfessorInvitations")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Backend.Administration.Entities.UniStaffInvitation", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithMany("UniStaffInvitations")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Auth.Entities.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("Backend.Auth.Entities.AdminUser", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithOne("AdminUser")
                        .HasForeignKey("Backend.Auth.Entities.AdminUser", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Backend.Auth.Entities.AuthIdentity", b =>
                {
                    b.HasOne("Backend.Auth.Entities.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Backend.Auth.Entities.ClassMetadata", b =>
                {
                    b.HasOne("Backend.Auth.Entities.Institute", "Institute")
                        .WithMany("AvailableClassSelection")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Professor", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithOne()
                        .HasForeignKey("Backend.Auth.Entities.Professor", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Student", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithOne("Student")
                        .HasForeignKey("Backend.Auth.Entities.Student", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Auth.Entities.UniClass", "UniClass")
                        .WithMany("Students")
                        .HasForeignKey("UniClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");

                    b.Navigation("UniClass");
                });

            modelBuilder.Entity("Backend.Auth.Entities.UniClass", b =>
                {
                    b.HasOne("Backend.Auth.Entities.ClassMetadata", "Metadata")
                        .WithMany("Classes")
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Backend.Auth.Entities.UniUser", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithOne("UniUser")
                        .HasForeignKey("Backend.Auth.Entities.UniUser", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Auth.Entities.Institute", "Institute")
                        .WithMany("Admins")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Identity");

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("Backend.StudentSpace.Entities.Course", b =>
                {
                    b.HasOne("Backend.Auth.Entities.Professor", "Professor")
                        .WithMany("Courses")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Auth.Entities.UniClass", "UniClass")
                        .WithMany("Courses")
                        .HasForeignKey("UniClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("UniClass");
                });

            modelBuilder.Entity("Backend.Auth.Entities.AuthIdentity", b =>
                {
                    b.Navigation("AdminUser");

                    b.Navigation("Notifications");

                    b.Navigation("ProfessorInvitations");

                    b.Navigation("Student");

                    b.Navigation("UniStaffInvitations");

                    b.Navigation("UniUser");
                });

            modelBuilder.Entity("Backend.Auth.Entities.ClassMetadata", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Institute", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("AvailableClassSelection");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Professor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Backend.Auth.Entities.UniClass", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
