// <auto-generated />
using System;
using Backend.Database.Auth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318012004_AddedReviewedBy")]
    partial class AddedReviewedBy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Admin.Entities.PendingJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityDocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentityReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InstituteCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstituteCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstitutePostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("ProofDocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("IdentityReviewedBy");

                    b.ToTable("PendingJoinRequests");
                });

            modelBuilder.Entity("Backend.Auth.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PfpUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Backend.Auth.Entities.AuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivateAccountToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivateAccountTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("Backend.Auth.Entities.ClassMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstituteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("LevelOfStudies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxYears")
                        .HasColumnType("integer");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("ClassMetadata");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Institute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lasttname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PfpUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("Backend.Auth.Entities.ProfessorUniClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfId")
                        .HasColumnType("uuid");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfId");

                    b.HasIndex("UniClassId");

                    b.ToTable("ProfessorUniClasses");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PfpUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("UniClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("UniClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Backend.Auth.Entities.SubjectPerClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassMetadataId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassMetadataId");

                    b.ToTable("SubjectPerClasses");
                });

            modelBuilder.Entity("Backend.Auth.Entities.UniClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("UniClasses");
                });

            modelBuilder.Entity("Backend.Auth.Entities.UniUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstutiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PfpUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("InstutiteId");

                    b.ToTable("UniUsers");
                });

            modelBuilder.Entity("Backend.Admin.Entities.PendingJoinRequest", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("IdentityReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Identity");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Backend.Auth.Entities.AdminUser", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithOne()
                        .HasForeignKey("Backend.Auth.Entities.AdminUser", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Backend.Auth.Entities.ClassMetadata", b =>
                {
                    b.HasOne("Backend.Auth.Entities.Institute", "Institute")
                        .WithMany("AvailableClassSelection")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Professor", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithOne()
                        .HasForeignKey("Backend.Auth.Entities.Professor", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Backend.Auth.Entities.ProfessorUniClass", b =>
                {
                    b.HasOne("Backend.Auth.Entities.Professor", "Prof")
                        .WithMany("Classes")
                        .HasForeignKey("ProfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Auth.Entities.UniClass", "UniClass")
                        .WithMany("Professors")
                        .HasForeignKey("UniClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prof");

                    b.Navigation("UniClass");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Student", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithOne()
                        .HasForeignKey("Backend.Auth.Entities.Student", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Auth.Entities.UniClass", "UniClass")
                        .WithMany("Students")
                        .HasForeignKey("UniClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");

                    b.Navigation("UniClass");
                });

            modelBuilder.Entity("Backend.Auth.Entities.SubjectPerClass", b =>
                {
                    b.HasOne("Backend.Auth.Entities.ClassMetadata", "ClassMetadata")
                        .WithMany("AvailableSubjects")
                        .HasForeignKey("ClassMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassMetadata");
                });

            modelBuilder.Entity("Backend.Auth.Entities.UniClass", b =>
                {
                    b.HasOne("Backend.Auth.Entities.ClassMetadata", "Metadata")
                        .WithMany("Classes")
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Backend.Auth.Entities.UniUser", b =>
                {
                    b.HasOne("Backend.Auth.Entities.AuthIdentity", "Identity")
                        .WithOne()
                        .HasForeignKey("Backend.Auth.Entities.UniUser", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Auth.Entities.Institute", "Institute")
                        .WithMany("Admins")
                        .HasForeignKey("InstutiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("Backend.Auth.Entities.ClassMetadata", b =>
                {
                    b.Navigation("AvailableSubjects");

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Institute", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("AvailableClassSelection");
                });

            modelBuilder.Entity("Backend.Auth.Entities.Professor", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Backend.Auth.Entities.UniClass", b =>
                {
                    b.Navigation("Professors");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
